### ISSUE TITLE
How to Map This

### ISSUE THREAD

**Issue by celticsamurai** [raleighlittles/Tourbox_Neo_Linux_Driver#4]
So I read that you can remap the buttons using Xmodmap. I've read up on the Arch wiki on how to use it, but it only seems to relate to the keyboard. I've also run xev just to get an idea as to the input, but some of them read the same (dial clockwise, knob counterclockwise). Anybody know where to point me for mapping this bad boy?

**Comment by raleighlittles** [comment]
Great question.

So to start, I was wrong about "XModMap" being used to map keys; [this answer](https://askubuntu.com/questions/24916/how-do-i-remap-certain-keys-or-devices) says that Ubuntu doesn't use XModMap anymore, and instead uses `xkb`. I'll update the README with this information.

The documentation lists the mapping between keys on the device and the actual Linux key/event code: https://github.com/raleighlittles/Tourbox_Linux_Driver/tree/main/docs#button-mapping

I tested this using `evtest`, I'm not familiar with `xev` though.

I have also actually never personally used `xkb`, but based on [this answer](https://askubuntu.com/questions/749660/how-can-i-persistently-remap-keys-in-ubuntu-16-04), it looks like one way to map keys would be to edit this file: `/usr/share/X11/xkb/keycodes/evdev`

This seems like it would be editing the global keyboard mapping though, which might not be what you want (this would make it so that the keys behave differently for each device, not just this one). I don't know the exact way to change keyboard mappings on a _per-device_ basis.

Depending on how involved the process is, it might just be easier for you to change the keyboard mappings to whatever you want in the code. Use the list of keys here: https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h

Hope that helps.

And then edit this map variable to be the new set of keys: https://github.com/raleighlittles/Tourbox_Linux_Driver/blob/main/cpp/uinput_helper.hpp#L43
